# Generated by Django 5.1.4 on 2025-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_data', models.DateField(auto_now_add=True)),
                ('Description', models.TextField()),
                ('quality', models.CharField(max_length=10, null=True)),
                ('duration', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
